name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Publish Release
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install MinGW (GCC)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: >-
            mingw-w64-x86_64-cmake
            git
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gles-headers
            mingw-w64-x86_64-egl-headers

      - name: Install Rust (GNU toolchain)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-pc-windows-gnu

      - name: Build Release Executable
        shell: msys2 {0}
        run: cargo build --release
        env:
          CMAKE: "C:\\msys64\\mingw64\\bin\\cmake.exe"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/sdl2xinput.exe
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
