name: Release

on:
  push:
    tags:
      - "v*" # This triggers the workflow when you push a tag like "v1.0.0"
  workflow_dispatch: # Also allows you to trigger it manually from the Actions tab

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Publish Release
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # SDL3 static building requires CMake, but windows-latest already has it installed!
      - name: Build Release Executable
        run: cargo build --release

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/sdl2xinput.exe
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
